# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='status',
            field=models.IntegerField(choices=[(1, 'Buka'), (0, 'Tutup')], default=0),
        ),
        migrations.AlterField(
            model_name='data',
            name='methane',
            field=models.IntegerField(default=0),
        ),
    ]
