# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 18:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170810_2306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='status',
            new_name='katup',
        ),
    ]
