# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_data_oxygen'),
    ]

    operations = [
        migrations.CreateModel(
            name='MethaneProduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('alat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Alat')),
            ],
        ),
        migrations.AddField(
            model_name='data',
            name='content',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='pressure',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='residu',
            field=models.IntegerField(default=0),
        ),
    ]
