# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20170811_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='methaneproduction',
            name='alat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Alat'),
        ),
    ]
