# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20170812_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='content',
        ),
        migrations.RemoveField(
            model_name='data',
            name='katup',
        ),
        migrations.RemoveField(
            model_name='data',
            name='oxygen',
        ),
        migrations.RemoveField(
            model_name='data',
            name='residu',
        ),
        migrations.AddField(
            model_name='data',
            name='power',
            field=models.BooleanField(choices=[(True, 'ON'), (False, 'OFF')], default=False),
        ),
        migrations.AddField(
            model_name='data',
            name='temperature',
            field=models.FloatField(default=0),
        ),
    ]
